Blog app - Views
Eccb7/Pi-Blogs pull request #6
Opened 2024-01-19 15:42 UTC by Eccb7

In this branch, I have 
- Implemented the design as from the sneak peek wireframe
- Used methods that I had created in the [Blog App - processing data in models](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/projects/Processing_data_model_project.md).

2024-01-19 17:20 UTC, Munsa1 requested changes
Hi @Eccb7 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
Added All Views :heavy_check_mark: 
Correct Git Flow :heavy_check_mark: 
Descriptive ReadMe File :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-01-19 17:20 UTC, Munsa1 commented on app/views/users/index.html.erb
> +</table>
- [ ] Kindly ensure your design follows the given wireframe in terms of layout of elements

your design
![image](https://github.com/Eccb7/Pi-Blogs/assets/81932478/cf50905d-c8fa-4030-9d84-0e77d014dc2f)

given design
![image](https://github.com/Eccb7/Pi-Blogs/assets/81932478/66b6489e-5ac2-4dd6-be3b-c3d6d639b1d9)

- Kindly ensure your `Number of posts` is aligned to the right as is in the given design
- Please fix the image on the user index page so that it shows

2024-01-19 17:20 UTC, Munsa1 commented on app/views/users/show.html.erb
> +</table>
- [ ] Kindly ensure that your design matches the given design in terms of elements and layouts to meet the requirements.

your design
![image](https://github.com/Eccb7/Pi-Blogs/assets/81932478/0ddca974-b1d7-4c5e-9067-0db6eee13ab2)

given frame
![image](https://github.com/Eccb7/Pi-Blogs/assets/81932478/8fc50fb6-171d-4680-bf2b-038e4a95f416)


- Kindly add the missing `Number of posts` in your design
- Use the `#recent_post` method in your user model to render the user's 3 most recent post.

2024-01-19 17:20 UTC, Munsa1 commented on app/views/posts/index.html.erb
> +        <p><strong>Number of posts:</strong> <%= @user.posts_counter %></p>
- [ ] Kindly ensure that your design matches the given design in terms of elements and layouts to meet the requirements.

- Kindly ensure your Number of posts is present and aligned to the right as is in the given design
- Your design should follow the following wireframe

Given
![image](https://github.com/Eccb7/Pi-Blogs/assets/81932478/2a5e97b7-b1b2-467b-90d3-a0bab2049c67)

Your design
![image](https://github.com/Eccb7/Pi-Blogs/assets/81932478/cafbb2c4-9264-40ce-bb3c-d584f58e71dc)

- Please use the recent comments method in your Post model to display the 5 most recent comments by a user

2024-01-19 17:20 UTC, Munsa1 commented on app/views/posts/show.html.erb
> +        </li>
- [ ] Again here kindly ensure you follow the given frame in terms of layout of items on the page so as to meet the requirements

Your design
![image](https://github.com/Eccb7/Pi-Blogs/assets/81932478/6b102786-183b-4243-b6bf-01849723717b)


Given design
![image](https://github.com/Eccb7/Pi-Blogs/assets/81932478/e122d788-ed0b-4965-a9fc-59891ed6f36e)

2024-01-20 20:29 UTC, OyePriscilla approved these changes
Hi @Eccb7 👏 👏, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![200](https://user-images.githubusercontent.com/103386183/196424328-985f6e98-f7c6-4cf9-bafe-158436f70560.gif)

## Highlights
Designed `views` according to the wireframe ✔️ 
`recent_comments` displayed in post_index page ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-01-20 20:33 UTC, merged